
import './globals.css'
import type { Metadata } from 'next'
import { Roboto_Condensed } from 'next/font/google'
import PesquisaProvider from './contexts/usePesquisaContexts'
import { Header } from './components/Header'
import { NavBar } from './components/NavBar'
import ImageBg from './components/ImageBg'
import { CarrinhoProvider } from './contexts/useCarrinhoContexts'

const roboto = Roboto_Condensed({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Caire Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <CarrinhoProvider>
      <PesquisaProvider>
        <html lang="en">
          <body className={roboto.className}>
            <Header />
            <NavBar />
            <ImageBg />
            {children}
          </body>
        </html>
      </PesquisaProvider>
    </CarrinhoProvider>
  )
}
